version: "3.3"
services:
  dns:
    build: 
      context: ./spring-boot-microservice-eureka-naming-server
      args:
        buildno: 1.0
    image: 127.0.0.1:5000/eureka-naming-server
    container_name: dns
    ports:
     - "8761:8761"
  ccs:
    build: ./currency-conversion
    image: 127.0.0.1:5000/currency-conversion-service
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
          
    depends_on:
      - dns
      - config
    environment:
      - eureka.client.service-url.defaultZone=http://dns:8761/eureka
    ports:
     - "8100:8100"
    volumes:
     - "/c/Users/HQZ/Documents/workspace-sts-3.9.4.RELEASE/CCSModule/spring-boot-microservice-currency-conversion-service/logs:/export/netsite/ext-admin/logs"
  
  forex:
    build: ./spring-boot-microservice-forex-service
    image: 127.0.0.1:5000/forex-service
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - dns
      - config
    environment:
      - eureka.client.service-url.defaultZone=http://dns:8761/eureka
    ports:
     - "8000:8000"
    volumes:
     - "/c/Users/HQZ/Documents/workspace-sts-3.9.4.RELEASE/CCSModule/spring-boot-microservice-forex-service/logs:/export/netsite/ext-admin/logs/"
  config:
    build: ./spring-cloud-config-server
    image: 127.0.0.1:5000/config-service
    container_name: config
    depends_on:
      - dns
    environment:
      - eureka.client.service-url.defaultZone=http://dns:8761/eureka
    ports:
     - "8222:8222"
    volumes:
      - type: bind
        source: /c/Users/HQZ/Documents/workspace-sts-3.9.4.RELEASE/CCSModule/config-repo
        target: /export/netsite/ext-admin/config/
  